---
abstract: ~
author:
  - 'clkao and jesse'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.26
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Prophet
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Any::Moose: 0.04
  Config::GitLike: 1.02
  DBD::SQLite: 1
  DBI: 1
  Digest::SHA: 0
  Exporter::Lite: 0
  ExtUtils::MakeMaker: 6.11
  File::ShareDir: 1.00
  HTTP::Date: 0
  HTTP::Server::Simple: 0.40
  IPC::Run3: 0
  JSON: 2.00
  JSON::XS: 2.2222
  LWP::UserAgent: 0
  MIME::Base64::URLSafe: 0
  Module::Pluggable: 0
  Module::Refresh: 0
  Mouse: 0.21
  Net::Bonjour: 0
  Params::Validate: 0
  Path::Dispatcher: 0.14
  Path::Dispatcher::Declarative: 0
  Proc::InvokeEditor: 0
  Template::Declare: 0.35
  Term::ReadKey: 0
  Term::ReadLine::Perl: 0
  Test::Exception: 0.26
  Test::HTTP::Server::Simple: 0
  Test::Pod::Coverage: 0
  Test::WWW::Mechanize: 1.16
  Time::Progress: 0
  URI: 0
  UUID::Tiny: 1.02
  XML::Atom::SimpleFeed: 0
  YAML::Syck: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.743
